In [1]:
import numpy as np

In [2]:
A=np.array([ [1,3,-2],[0,4,7],[-1,2,6] ])
B=np.array([ [0,1],[1,3],[2,1] ])
#(1)Find the component-wise sum of the matrix A with itself.
print(np.add(A,A))

[[ 2  6 -4]
 [ 0  8 14]
 [-2  4 12]]


In [3]:
#(2)Find the transpose of each of matrix A and matrix B.
print(A.T)
print(B.T)

[[ 1  0 -1]
 [ 3  4  2]
 [-2  7  6]]
[[0 1 2]
 [1 3 1]]


In [4]:
#(3)Find the inverse of matrix A.
print(np.asmatrix(A).I)


[[-0.52631579  1.15789474 -1.52631579]
 [ 0.36842105 -0.21052632  0.36842105]
 [-0.21052632  0.26315789 -0.21052632]]


In [5]:
#(4)Find the matrix product AB.
print(np.asmatrix(A)*np.asmatrix(B))
print(np.dot(A,B))

[[-1  8]
 [18 19]
 [14 11]]
[[-1  8]
 [18 19]
 [14 11]]


In [6]:
#(5)Reshape the matrix B to be of size 2 x 3 (as opposed to its current size of 3 x 2).  Store the result as matrix C.
C=np.reshape(B,(2,3))
print(C)

[[0 1 1]
 [3 2 1]]


In [7]:
#(6)Find the matrix product CA. 
print(np.asmatrix(C)*np.asmatrix(A))

[[-1  6 13]
 [ 2 19 14]]


In [8]:
#(7)Replace all the odd entries of matrix A with the value -1.  Store the result as matrix D.
D=np.where(A % 2 !=0,-1,A)
#print(A)
print(D)

[[-1 -1 -2]
 [ 0  4 -1]
 [-1  2  6]]


In [9]:
#(8)Create a new matrix whose entries are the sums of the rows of matrix A.
E=np.sum(A,axis=1)
print(E)

[ 2 11  7]


In [10]:
#(9)Create a new matrix whose entries are the means of the columns of matrix A.
F=np.mean(A,axis=0)
print(F)

[0.         3.         3.66666667]


In [11]:
#(10)Find the component-wise square root of matrix B.
print(np.sqrt(B))
print(B)

[[0.         1.        ]
 [1.         1.73205081]
 [1.41421356 1.        ]]
[[0 1]
 [1 3]
 [2 1]]
